MODEL:
  TYPE: generalized_rcnn
  SUBTYPE: 3
  USE_OVLP_FILTER: True
  USE_FREQ_BIAS: True
  NO_FC7_RELU: True
  USE_SPATIAL_FEAT: True
  ADD_SO_SCORES: True
  ADD_SCORES_ALL: True
  USE_BG: True
  CONV_BODY: FPN.fpn_ResNet101_conv5_body
  FASTER_RCNN: True
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER: 36000
  STEPS: [0, 24000]  # [0, 48000, 64000]
  COSINE_LR: True
  COSINE_NUM_EPOCH: 13
  COSINE_T0: 3
  COSINE_MULTI: 2
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
RESNETS:
  VG_PRETRAINED_WEIGHTS: 'Outputs/e2e_faster_rcnn_X-101-64x4d-FPN_2x_gqa_no_plural/gqa_no_plural/Jun10-20-19-50_learnfair0493_step/ckpt/model_step149999.pth'
  VG_PRD_PRETRAINED_WEIGHTS: 'Outputs/e2e_faster_rcnn_X-101-64x4d-FPN_2x_gqa_no_plural/gqa_no_plural/Jun10-20-19-50_learnfair0493_step/ckpt/model_step149999.pth'
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 64
  WIDTH_PER_GROUP: 4
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  SCALES: (800,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  FORCE_JSON_DATASET_EVAL: True
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
